name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
      GOOGLE_PASS: ${{ secrets.GOOGLE_PASS }}
      GOOGLE_PHONE: ${{ secrets.GOOGLE_PHONE }}
      DISPLAY: ":99"
      SCREEN_RES: "1920x1080x24"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgbm-dev libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgtk-3-0 libasound2t64

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Start Xvfb
        run: |
          Xvfb $DISPLAY -screen 0 $SCREEN_RES -ac -nolisten tcp &
          sleep 5

      - name: Run tests with Xvfb
        run: |
          export DISPLAY=$DISPLAY
          xvfb-run --auto-servernum \
          pytest -m smoke --alluredir=reports \
          --browser=chromium \
          --headed \
          --slowmo=1000 \

      - name: Upload screenshots on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots/

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure_report
          path: reports/

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: reports
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-history
